### ISSUE TITLE
Making the admin role configurable in Fixture

### ISSUE THREAD

**Issue by mamazu** [Sylius/RbacPlugin#54]
It would be helpful if you could specify the role an admin has in the fixtures of the admin.
```yml
admin_user:
          options:
            custom:
              - email: 'test@sylius.com'
                username: 'sylius'
                password: 'sylius'
                enabled: true
                locale_code: 'en_US'
                first_name: 'Testuser'
                last_name: 'Brille24'
                role: 'configurator'
```
